# numpy란?
* Numerical Python 과학적, 산업적 연산을 위한 파이썬 패키지
* 다차원 배열, 행렬 연산에 주로 사용

In [ ]:
# !pip install numpy
# !conda install numpy

# 차원

* 0차원 = 점

* 1차원 = 선
* 벡터는 방향을 가진 데이터

* 2차원 = 면 matrix, dataframe

* 3차원 = 공간, 입체

* 4차원 = 3차원 요소가 2개 이상

In [6]:
import numpy as np

In [7]:
a = np.array([1,2,3,4,5])

In [8]:
a

array([1, 2, 3, 4, 5])

In [9]:
a.ndim

1

In [10]:
b = 32

In [11]:
b.ndim

AttributeError: 'int' object has no attribute 'ndim'

In [19]:
c = np.array([[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]])
c

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [20]:
c.ndim

2

In [27]:
c.shape

(2, 5)

In [22]:
d = np.array([[[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]],[[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]]])
d

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [23]:
d.ndim

3

In [28]:
d.shape

(2, 2, 5)

In [1]:
e = np.array([[[[1,2,3,4,5],[1,2,3,4,5]], [[1,2,3,4,5],[1,2,3,4,5]]], [[[1,2,3,4,5],[1,2,3,4,5]], [[1,2,3,4,5],[1,2,3,4,5]]]])
e

NameError: name 'np' is not defined

In [ ]:
e.ndim

In [ ]:
e.shape

In [ ]:
f = np.array([[[[[1,2,3,4,5],[1,2,3,4,5]], [[1,2,3,4,5],[1,2,3,4,5]]], [[[1,2,3,4,5],[1,2,3,4,5]], [[1,2,3,4,5],[1,2,3,4,5]]]], [[[[1,2,3,4,5],[1,2,3,4,5]], [[1,2,3,4,5],[1,2,3,4,5]]], [[[1,2,3,4,5],[1,2,3,4,5]], [[1,2,3,4,5],[1,2,3,4,5]]]]])
f

In [ ]:
f.ndim

In [ ]:
f.shape

numpy를 사용하는 이유: 행렬 연산이 쉽고 빠르기 때문

* 스칼라와 연산

In [29]:
a = 10

In [30]:
scalar = a + 1
scalar

11

* 벡터연산

In [32]:
b = np.array([1,2,3,4,5,])
b

array([1, 2, 3, 4, 5])

In [34]:
c = [5,6,7,8,9]

In [35]:
hap = []
for num in c:
    hap.append(num + 3)
hap

[8, 9, 10, 11, 12]

In [36]:
b + 3

array([4, 5, 6, 7, 8])

In [37]:
b * 8

array([ 8, 16, 24, 32, 40])

* 2차원 연산 +5 하기

In [38]:
d = [[1,2,3],[1,2,3],[1,2,3]]
d

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [44]:
hap = []
for i in d:
    temp = []
    for j in i:
        temp.append(j+5)
    hap.append(temp)
hap

[[6, 7, 8], [6, 7, 8], [6, 7, 8]]

In [39]:
d2 = np.array([[1,2,3],[1,2,3],[1,2,3]])
d2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [45]:
d2 + 5

array([[6, 7, 8],
       [6, 7, 8],
       [6, 7, 8]])

# numpy에서 자주 사용하드 매서드
* .ndim : 몇 차원인지 보는 것
* .shape : 몇 차원, 몇 행 몇 열로 되어 있는지 구조 확인
* .size : 배열 안에 있는 요소의 총 개수가 몇 개인지
* .dtype : 데이터 타입이 무엇
* .itemsize : 1개 자료의 크기는 몇인지

In [47]:
d2.ndim

2

In [46]:
d2.shape

(3, 3)

In [48]:
d2.size

9

In [49]:
d2.dtype

dtype('int64')

In [2]:
# item 한 개의 바이트 수
d2.itemsize

NameError: name 'd2' is not defined

In [52]:
d3 = d2 / 2
d3

array([[0.5, 1. , 1.5],
       [0.5, 1. , 1.5],
       [0.5, 1. , 1.5]])

# np.array 만들기
* np.aaray(리스트/튜플)
* 자료형은 반드시 1가지만 넣는다.

In [53]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [54]:
np.array([1,2,3,4,5.3])

array([1. , 2. , 3. , 4. , 5.3])

In [58]:
e = np.array([1,2,3,4,5])
e.dtype

dtype('int64')

In [60]:
e2 = np.array([1,2,3,4,5.3])
print(e2.dtype)
print(e2)

float64
[1.  2.  3.  4.  5.3]


In [63]:
e3 = np.array([1,2,'3',4,5.3])
print(e3.dtype)
print(type(e3))
e3

<U32
<class 'numpy.ndarray'>


array(['1', '2', '3', '4', '5.3'], dtype='<U32')

In [64]:
for i in e3:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


* np.arrange(시작, 끝+1, step)

In [67]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [69]:
np.arange(3,101,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

* .reshape(행, 열) 벡터를 원하는 크기의 matrix 또는 다차원 배열로 변환

In [71]:
a = np.arange(24)
print(a)
print(a.ndim)
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
(24,)


In [74]:
b = a.reshape(3,8)
print(b)
print(b.ndim)
print(b.shape)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
2
(3, 8)


In [81]:
c = a.reshape(3,2,2,2)
print(c)
print(c.ndim)
print(c.shape)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]


 [[[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]
4
(3, 2, 2, 2)


In [82]:
d = c.reshape(24)
print(d)
print(d.ndim)
print(d.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
(24,)


* flatten() 다차원 데이터를 1차원 배열로 바꿔주는 함수

In [83]:
c.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

* np.flip() 행렬의 순서를 뒤집을 때

In [84]:
np.flip(c)

array([[[[23, 22],
         [21, 20]],

        [[19, 18],
         [17, 16]]],


       [[[15, 14],
         [13, 12]],

        [[11, 10],
         [ 9,  8]]],


       [[[ 7,  6],
         [ 5,  4]],

        [[ 3,  2],
         [ 1,  0]]]])

In [85]:
c[::-1]

array([[[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]]])

정해진 숫자 범위 안에서 균등하게 구간을 나눌 때
* np.linspace(시작, 끝, 구간 수)

In [86]:
np.linspace(0, 1, 123)

array([0.        , 0.00819672, 0.01639344, 0.02459016, 0.03278689,
       0.04098361, 0.04918033, 0.05737705, 0.06557377, 0.07377049,
       0.08196721, 0.09016393, 0.09836066, 0.10655738, 0.1147541 ,
       0.12295082, 0.13114754, 0.13934426, 0.14754098, 0.1557377 ,
       0.16393443, 0.17213115, 0.18032787, 0.18852459, 0.19672131,
       0.20491803, 0.21311475, 0.22131148, 0.2295082 , 0.23770492,
       0.24590164, 0.25409836, 0.26229508, 0.2704918 , 0.27868852,
       0.28688525, 0.29508197, 0.30327869, 0.31147541, 0.31967213,
       0.32786885, 0.33606557, 0.3442623 , 0.35245902, 0.36065574,
       0.36885246, 0.37704918, 0.3852459 , 0.39344262, 0.40163934,
       0.40983607, 0.41803279, 0.42622951, 0.43442623, 0.44262295,
       0.45081967, 0.45901639, 0.46721311, 0.47540984, 0.48360656,
       0.49180328, 0.5       , 0.50819672, 0.51639344, 0.52459016,
       0.53278689, 0.54098361, 0.54918033, 0.55737705, 0.56557377,
       0.57377049, 0.58196721, 0.59016393, 0.59836066, 0.60655

In [89]:
f = np.array([5,7,11,1,3,2,54,0.5,0.6])
f

array([ 5. ,  7. , 11. ,  1. ,  3. ,  2. , 54. ,  0.5,  0.6])

In [90]:
f.sort

<function ndarray.sort>

# argsort() 자료 중 값이 작은 것에서 큰 순으로 원래 인덱스 출력

In [99]:
g = np.array([5, 0.5, -7, 42, 10, 0])
print(g)
s = g.argsort()
print(s)

[ 5.   0.5 -7.  42.  10.   0. ]
[2 5 1 0 4 3]


In [94]:
g.argsort()

array([2, 1, 0, 4, 3])

In [97]:
g2 = g[sorted(g.argsort())]
g2

array([ 5. ,  0.5, -7. , 42. , 10. ])

# 배열 합치기
* np.concatenate()

In [102]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(a.shape)
print(b)
print(b.shape)

[[1 2]
 [3 4]]
(2, 2)
[[5 6]
 [7 8]]
(2, 2)


* np.concatenate((a,b)) 의 기본 병합 방향은 행방향, axis = 0
* 행방향으로 합칠 때는 두 행렬의 열의 길이가 같아야 합쳐짐

In [109]:
concat_row = np.concatenate((a,b))
print(concat_row)
print(concat_row.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


* axis=1은 열방향으로 붙음
* 두 행렬의 행 길이가 같아야 붙음

In [110]:
concat_col = np.concatenate((a,b), axis=1)
print(concat_col)
print(concat_col.shape)

[[1 2 5 6]
 [3 4 7 8]]
(2, 4)


# 합치는 방향의 모양이 일치하지 않으면 합치기 X

In [112]:
c = np.array([[1,2],[3,4]])
d = np.array([[5,6]])
print(c)
print(c.shape)
print(d)
print(d.shape)

[[1 2]
 [3 4]]
(2, 2)
[[5 6]]
(1, 2)


In [116]:
concat_row2 = np.concatenate((c,d), axis=0)
print(concat_row2)
print(concat_row2.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [124]:
concat_col2 = np.concatenate((c,d.T), axis=1)
print(concat_col2)
print(concat_col2.shape)

[[1 2 5]
 [3 4 6]]
(2, 3)


## 벡터와 매트릭스는 합칠 수 없다.

In [119]:
e = np.array([[1,2],[3,4]])
f = np.array([5,6])
print(e)
print(e.shape)
print(e.ndim)
print(f)
print(f.shape)
print(f.ndim)

[[1 2]
 [3 4]]
(2, 2)
[5 6]
(2,)


In [121]:
concat_row3 = np.concatenate((e,f), axis=0)
print(concat_row3)
print(concat_row3.shape)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

# 전치 행렬 만들기
* .T
* .transpose()
* .reshape()

In [130]:
h = np.array([[5,6,7]])

In [131]:
print(h)
print(h.shape)

[[5 6 7]]
(1, 3)


In [136]:
h2 = h.T
print(h2)
print(h2.shape)

[[5]
 [6]
 [7]]
(3, 1)


In [132]:
h3 = h.transpose()
print(h3)
print(h3.shape)

[[5]
 [6]
 [7]]
(3, 1)


In [134]:
h4 = h.reshape(3,1)
print(h4)
print(h4.shape)

[[5]
 [6]
 [7]]
(3, 1)


In [135]:
i = np.arange(6).reshape(3,2)
print(i)
print(i.shape)
print(i.ndim)

[[0 1]
 [2 3]
 [4 5]]
(3, 2)
2


In [137]:
i2 = i.T
print(i2)
print(i2.shape)

[[0 2 4]
 [1 3 5]]
(2, 3)


In [138]:
i3 = i.transpose()
print(i3)
print(i3.shape)

[[0 2 4]
 [1 3 5]]
(2, 3)


In [140]:
i4 = i.reshape(2,3)
print(i4)
print(i4.shape)

[[0 1 2]
 [3 4 5]]
(2, 3)


# 브로드 캐스팅
* 벡터와 스칼라, 또는 매트릭스와 벡터를 연산할 때 자동으로 행렬 크기를 맞춰주는 것

In [143]:
a = np.arange(1,16).reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [144]:
a + 3

array([[ 4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18]])

In [146]:
b =  np.array([1,2,3,4,5])
print(a.shape)
print(b.shape)
a + b

(3, 5)
(5,)


array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13, 15],
       [12, 14, 16, 18, 20]])